[package]
name = "storage-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Client library for scalable Web3 storage"

[dependencies]
storage-primitives = { workspace = true, features = ["std", "serde"] }
reqwest = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true }
sp-core = { workspace = true, features = ["std"] }
tokio = { workspace = true }
base64 = "0.22"
thiserror = "2.0"
tracing = "0.1"
rand = "0.8"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
storage-provider-node = { workspace = true }
axum = { workspace = true }
