inlineHeader = "SPDX-License-Identifier: Apache-2.0"
keywords = ["SPDX-License-Identifier"]

includes = [
	"**/*.js",
	"**/*.rs",
	"**/*.sol",
	"**/*.ts",
	"**/*.tsx",
]
excludes = [
	"**/*.bin.ts",
	"**/*weight.rs",
	"runtimes/web3-paseo-local/src/weights/*.rs",
	"runtimes/web3-storage-local/src/weights/*.rs",
]

[mapping.DOUBLESLASH_STYLE]
extensions = ["js", "sol", "ts", "tsx"]
