# Before running:
# export POLKADOT_BINARY_PATH=~/Projects/polkadot-sdk/target/release/polkadot or similar

[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "{{POLKADOT_BINARY_PATH}}"
chain = "westend-local"
default_args = ["--network-backend=libp2p"]

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  rpc_port = 9900

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  rpc_port = 9901

[[parachains]]
id = 4000
chain_spec_path = "chain-specs/storage-local.json"
cumulus_based = true
onboard_as_parachain = true

  [parachains.collator]
  name = "storage-collator"
  command = "polkadot-omni-node"
  rpc_port = 9944
  args = ["--collator", "--no-mdns", "--network-backend=libp2p"]
