[settings]
timeout = 1000
provider = "native"
node_spawn_timeout = 240

[relaychain]
default_command = "{{PROJECT_ROOT}}/.bin/polkadot"
chain = "westend-local"
default_args = ["-lruntime=info"]

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
num_cores = 3

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
allowed_ancestry_len = 6
max_candidate_depth = 6

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9900

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9901

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[relaychain.nodes]]
name = "eve"
validator = true

[[relaychain.nodes]]
name = "ferdie"
validator = true

[[parachains]]
id = 4000
cumulus_based = true
num_cores = 3
chain_spec_command = "{{PROJECT_ROOT}}/scripts/build-chain-spec.sh"

[[parachains.collators]]
name = "alice"
validator = true
command = "{{PROJECT_ROOT}}/.bin/polkadot-omni-node"
rpc_port = 2222
args = ["--authoring=slot-based", "--collator", "-lruntime=info"]

[[parachains.collators]]
name = "bob"
validator = true
command = "{{PROJECT_ROOT}}/.bin/polkadot-omni-node"
args = ["--authoring=slot-based", "--collator", "-lruntime=info"]
