// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `be7eda576c79`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/storage-parachain-runtime/storage_parachain_runtime.wasm
// --pallet=pallet_storage_provider
// --header=/__w/web3-storage/web3-storage/scripts/cmd/file_header.txt
// --output=./runtimes/web3-storage-local/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_storage_provider`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_storage_provider::WeightInfo for WeightInfo<T> {
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::ProviderReplayStates` (r:0 w:1)
	/// Proof: `StorageProvider::ProviderReplayStates` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn register_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `145`
		//  Estimated: `3825`
		// Minimum execution time: 30_954_000 picoseconds.
		Weight::from_parts(32_457_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn deregister_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3825`
		// Minimum execution time: 14_743_000 picoseconds.
		Weight::from_parts(15_703_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:0)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayStates` (r:0 w:1)
	/// Proof: `StorageProvider::ProviderReplayStates` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn complete_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `3825`
		// Minimum execution time: 32_774_000 picoseconds.
		Weight::from_parts(34_473_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn cancel_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `289`
		//  Estimated: `3825`
		// Minimum execution time: 12_382_000 picoseconds.
		Weight::from_parts(13_148_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_settings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3825`
		// Minimum execution time: 12_513_000 picoseconds.
		Weight::from_parts(13_354_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn add_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `388`
		//  Estimated: `3825`
		// Minimum execution time: 26_752_000 picoseconds.
		Weight::from_parts(28_061_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	fn block_extensions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `3825`
		// Minimum execution time: 19_500_000 picoseconds.
		Weight::from_parts(21_661_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_multiaddr() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3825`
		// Minimum execution time: 12_929_000 picoseconds.
		Weight::from_parts(13_892_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_bucket_min_providers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 9_556_000 picoseconds.
		Weight::from_parts(10_301_000, 0)
			.saturating_add(Weight::from_parts(0, 3823))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn freeze_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `543`
		//  Estimated: `4008`
		// Minimum execution time: 14_931_000 picoseconds.
		Weight::from_parts(16_577_000, 0)
			.saturating_add(Weight::from_parts(0, 4008))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn set_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `11515`
		// Minimum execution time: 18_470_000 picoseconds.
		Weight::from_parts(19_615_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn remove_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `11515`
		// Minimum execution time: 19_377_000 picoseconds.
		Weight::from_parts(20_588_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_slashed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `947`
		//  Estimated: `4412`
		// Minimum execution time: 45_046_000 picoseconds.
		Weight::from_parts(48_952_000, 0)
			.saturating_add(Weight::from_parts(0, 4412))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayStates` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayStates` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	fn establish_storage_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `563`
		//  Estimated: `11515`
		// Minimum execution time: 99_755_000 picoseconds.
		Weight::from_parts(102_905_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayStates` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayStates` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn establish_replica_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `879`
		//  Estimated: `4344`
		// Minimum execution time: 102_655_000 picoseconds.
		Weight::from_parts(106_347_000, 0)
			.saturating_add(Weight::from_parts(0, 4344))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `3825`
		// Minimum execution time: 38_474_000 picoseconds.
		Weight::from_parts(42_330_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn extend_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `3825`
		// Minimum execution time: 38_820_000 picoseconds.
		Weight::from_parts(42_630_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:0)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 1]`.
	fn end_agreement(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1050 + a * (103 ±0)`
		//  Estimated: `6196 + a * (2603 ±0)`
		// Minimum execution time: 89_006_000 picoseconds.
		Weight::from_parts(98_509_324, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 443_377
			.saturating_add(Weight::from_parts(40_408_775, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:0)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_expired_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1079`
		//  Estimated: `6196`
		// Minimum execution time: 87_839_000 picoseconds.
		Weight::from_parts(96_387_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1730`
		//  Estimated: `15165`
		// Minimum execution time: 258_237_000 picoseconds.
		Weight::from_parts(267_891_000, 0)
			.saturating_add(Weight::from_parts(0, 15165))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn extend_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1784`
		//  Estimated: `15165`
		// Minimum execution time: 280_232_000 picoseconds.
		Weight::from_parts(286_322_000, 0)
			.saturating_add(Weight::from_parts(0, 15165))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextChallengeIndex` (r:1 w:1)
	/// Proof: `StorageProvider::NextChallengeIndex` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:0 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	fn challenge_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1001`
		//  Estimated: `4466`
		// Minimum execution time: 57_224_000 picoseconds.
		Weight::from_parts(62_969_000, 0)
			.saturating_add(Weight::from_parts(0, 4466))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextChallengeIndex` (r:1 w:1)
	/// Proof: `StorageProvider::NextChallengeIndex` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:0 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	fn challenge_off_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `683`
		//  Estimated: `4148`
		// Minimum execution time: 101_892_000 picoseconds.
		Weight::from_parts(105_667_000, 0)
			.saturating_add(Weight::from_parts(0, 4148))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextChallengeIndex` (r:1 w:1)
	/// Proof: `StorageProvider::NextChallengeIndex` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:0 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	fn challenge_replica() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `848`
		//  Estimated: `3825`
		// Minimum execution time: 58_097_000 picoseconds.
		Weight::from_parts(62_884_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn respond_to_challenge_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1102`
		//  Estimated: `8799`
		// Minimum execution time: 1_179_799_000 picoseconds.
		Weight::from_parts(1_200_993_000, 0)
			.saturating_add(Weight::from_parts(0, 8799))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn respond_to_challenge_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1315`
		//  Estimated: `8799`
		// Minimum execution time: 142_078_000 picoseconds.
		Weight::from_parts(146_544_000, 0)
			.saturating_add(Weight::from_parts(0, 8799))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:1 w:1)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:1 w:1)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn respond_to_challenge_superseded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156`
		//  Estimated: `8799`
		// Minimum execution time: 92_281_000 picoseconds.
		Weight::from_parts(100_012_000, 0)
			.saturating_add(Weight::from_parts(0, 8799))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainSystem::LastRelayChainBlockNumber` (r:1 w:0)
	/// Proof: `ParachainSystem::LastRelayChainBlockNumber` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn confirm_replica_sync() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `970`
		//  Estimated: `6196`
		// Minimum execution time: 77_358_000 picoseconds.
		Weight::from_parts(84_829_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(243), added: 2718, mode: `MaxEncodedLen`)
	fn top_up_replica_sync_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `506`
		//  Estimated: `3708`
		// Minimum execution time: 31_884_000 picoseconds.
		Weight::from_parts(34_745_000, 0)
			.saturating_add(Weight::from_parts(0, 3708))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ParachainSystem::ValidationData` (r:1 w:0)
	/// Proof: `ParachainSystem::ValidationData` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::LastSweptChallengeBlock` (r:1 w:1)
	/// Proof: `StorageProvider::LastSweptChallengeBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:101 w:100)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallenges` (r:100 w:100)
	/// Proof: `StorageProvider::PendingChallenges` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::PendingChallengesByBucket` (r:100 w:100)
	/// Proof: `StorageProvider::PendingChallengesByBucket` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:100 w:100)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:201 w:201)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ChallengerStats` (r:100 w:100)
	/// Proof: `StorageProvider::ChallengerStats` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextChallengeIndex` (r:0 w:1)
	/// Proof: `StorageProvider::NextChallengeIndex` (`max_values`: None, `max_size`: Some(22), added: 2497, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 100]`.
	fn on_initialize_slash_challenges(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `83 + c * (803 ±0)`
		//  Estimated: `3639 + c * (5206 ±0)`
		// Minimum execution time: 11_348_000 picoseconds.
		Weight::from_parts(11_414_000, 0)
			.saturating_add(Weight::from_parts(0, 3639))
			// Standard Error: 32_311
			.saturating_add(Weight::from_parts(66_113_342, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((7_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 5206).saturating_mul(c.into()))
	}
}
