#!/bin/bash
#
# Renders every diagram spec in docs/site/specs/ to docs/site/ with archify.
#
# Spec file names are NN-<name>.<type>.json; the page is docs/site/NN-<name>.html.
# The CSS and scripts that are the same on every page go to docs/site/assets/archify/
# (see scripts/split-docs-page.mjs), so each page contains only its diagram and data.
#
# Usage:
#   scripts/build-docs-site.sh                      # all specs
#   scripts/build-docs-site.sh 03 11                # only pages 03 and 11
#   scripts/build-docs-site.sh --visual-check 03    # also run the browser check
#
# Uses archify at the commit pinned in .claude/skills/generate-docs/archify.lock,
# from the directory that scripts/archify-dir.sh prints. When no copy exists,
# scripts/verify-archify.sh --install checks and installs the pinned commit.
# The script fails if the installed copy differs. See the generate-docs skill.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

ARCHIFY_DIR=$(scripts/archify-dir.sh)
ARCHIFY_BIN="$ARCHIFY_DIR/bin/archify.mjs"
LOCK=.claude/skills/generate-docs/archify.lock
# archify's update check contacts its release server; the build never needs it.
export ARCHIFY_UPDATE_CHECK_DISABLED=1

if [[ ! -d "$ARCHIFY_DIR" ]]; then
  echo "archify not found at $ARCHIFY_DIR; installing the pinned commit" >&2
  ARCHIFY_DIR="$ARCHIFY_DIR" scripts/verify-archify.sh --install
fi
if [[ ! -f "$ARCHIFY_BIN" ]]; then
  echo "archify at $ARCHIFY_DIR has no bin/archify.mjs; see .claude/skills/generate-docs/SKILL.md" >&2
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# The installed files must be the verified commit: compare git tree hashes.
pinned_tree=$(sed -n 's/^tree=//p' "$LOCK")
installed_tree=$(scripts/archify-tree-hash.sh "$ARCHIFY_DIR")
if [[ "$installed_tree" != "$pinned_tree" ]]; then
  echo "archify at $ARCHIFY_DIR (tree $installed_tree) is not the verified commit in $LOCK (tree $pinned_tree)." >&2
  echo "Run scripts/verify-archify.sh and follow the generate-docs skill." >&2
  exit 1
fi

visual_check=0
if [[ "${1:-}" == "--visual-check" ]]; then
  visual_check=1
  shift
fi

# Every page number given must match a spec.
for n in "$@"; do
  compgen -G "docs/site/specs/$n-*.json" > /dev/null || { echo "no spec matches page $n" >&2; exit 1; }
done

mkdir -p "$tmp/assets/archify"
cp docs/site/assets/diagram-page.css "$tmp/assets/"

failed=0
for spec in docs/site/specs/*.json; do
  base=$(basename "$spec" .json)   # NN-name.type
  page=${base%.*}                  # NN-name
  type=${base##*.}                 # type
  if [[ $# -gt 0 ]]; then
    match=0
    for n in "$@"; do [[ "$page" == "$n"-* ]] && match=1; done
    [[ $match -eq 1 ]] || continue
  fi

  # A brand object makes archify fetch a URL during deliver.
  if node -e '
    const has = (v) => v && typeof v === "object" &&
      (Object.hasOwn(v, "brand") || Object.values(v).some(has));
    process.exit(has(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))) ? 0 : 1);
  ' "$spec"; then
    echo "FAIL $page: specs must not use \"brand\"" >&2
    failed=1
    continue
  fi

  if ! node "$ARCHIFY_BIN" deliver "$type" "$spec" "$tmp/$page.html" --quality showcase --json > "$tmp/$page.receipt.json"; then
    echo "FAIL $page: archify deliver failed, see:" >&2
    cat "$tmp/$page.receipt.json" >&2
    failed=1
    continue
  fi

  perl -0pi -e '
    s/ARCHIFY/WEB3 STORAGE/g;
    s/ generated by Archify\././g;
  ' "$tmp/$page.html"

  if grep -qE 'ARCHIFY|by Archify' "$tmp/$page.html"; then
    echo "FAIL $page: visible archify text remains in the page" >&2
    failed=1
    continue
  fi

  if ! node scripts/split-docs-page.mjs "$tmp/$page.html" "$tmp/assets/archify"; then
    echo "FAIL $page: cannot move the shared CSS and scripts out of the page" >&2
    failed=1
    continue
  fi

  # A build of some pages must produce the shared files already in docs/site/,
  # because the other pages use them too.
  if [[ $# -gt 0 ]] && ! diff -rq "$tmp/assets/archify" docs/site/assets/archify > /dev/null 2>&1; then
    echo "FAIL $page: the shared files differ from docs/site/assets/archify/; rebuild all pages (no page numbers)" >&2
    failed=1
    continue
  fi

  # Link back to the landing page, above the page title.
  if [[ $(grep -o '<div class="header">' "$tmp/$page.html" | wc -l) -ne 1 || $(grep -o '</head>' "$tmp/$page.html" | wc -l) -ne 1 ]]; then
    echo "FAIL $page: page layout changed; cannot add the link to index.html" >&2
    failed=1
    continue
  fi
  perl -0pi -e '
    s{</head>}{  <link rel="stylesheet" href="assets/diagram-page.css">\n</head>};
    s{<div class="header">}{<div class="header">\n      <p class="site-crumb"><a href="index.html">&larr; Scalable Web3 Storage</a></p>};
  ' "$tmp/$page.html"

  if [[ $visual_check -eq 1 ]]; then
    if node "$ARCHIFY_BIN" visual-check "$tmp/$page.html" --json > "$tmp/$page.visual.json"; then
      echo "ok   $page: visual-check passed"
      rm -f "$tmp/$page".visual-check.*
    else
      echo "FAIL $page: visual-check did not pass; page not written:" >&2
      grep -oE '"code": *"[^"]*"' "$tmp/$page.visual.json" | sort | uniq -c >&2 || true
      failed=1
      continue
    fi
  fi

  # A build of some pages writes each page now: it keeps the shared files.
  # A full build writes all pages and the shared files at the end.
  if [[ $# -gt 0 ]]; then
    mv "$tmp/$page.html" "docs/site/$page.html"
    echo "ok   docs/site/$page.html"
  else
    echo "ok   $page"
  fi
done

# split-docs-page.mjs has checked that every page produced the same shared files.
if [[ $# -eq 0 ]]; then
  if [[ $failed -ne 0 ]]; then
    echo "FAIL: a page failed; docs/site/ is unchanged" >&2
    exit 1
  fi
  for spec in docs/site/specs/*.json; do
    page=$(basename "$spec" .json)
    page=${page%.*}
    mv "$tmp/$page.html" "docs/site/$page.html"
  done
  rm -rf docs/site/assets/archify
  cp -R "$tmp/assets/archify" docs/site/assets/archify
  echo "ok   docs/site/: all pages and docs/site/assets/archify/"
fi

exit $failed
