// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-28, STEPS: `10`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.0.104`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/storage-paseo-runtime/storage_paseo_runtime.compact.wasm
// --pallet
// pallet_storage_provider
// --extrinsic
// *
// --steps
// 10
// --repeat
// 2
// --output
// pallet/src/weights.rs
// --template=templates/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_storage_provider`.
pub trait WeightInfo {
	fn register_provider() -> Weight;
	fn deregister_provider() -> Weight;
	fn complete_deregister() -> Weight;
	fn cancel_deregister() -> Weight;
	fn update_provider_settings() -> Weight;
	fn add_stake() -> Weight;
	fn block_extensions() -> Weight;
	fn update_provider_multiaddr() -> Weight;
	fn set_bucket_min_providers() -> Weight;
	fn freeze_bucket() -> Weight;
	fn set_bucket_member() -> Weight;
	fn remove_bucket_member() -> Weight;
	fn remove_slashed() -> Weight;
	fn establish_storage_agreement() -> Weight;
	fn establish_replica_agreement() -> Weight;
	fn top_up_agreement() -> Weight;
	fn extend_agreement() -> Weight;
	fn end_agreement(a: u32, ) -> Weight;
	fn claim_expired_agreement() -> Weight;
	fn checkpoint() -> Weight;
	fn extend_checkpoint() -> Weight;
	fn fund_checkpoint_pool() -> Weight;
	fn provider_checkpoint(s: u32, ) -> Weight;
	fn configure_checkpoint_window() -> Weight;
	fn report_missed_checkpoint() -> Weight;
	fn claim_checkpoint_rewards() -> Weight;
	fn challenge_checkpoint() -> Weight;
	fn challenge_off_chain() -> Weight;
	fn challenge_replica() -> Weight;
	fn respond_to_challenge_proof() -> Weight;
	fn respond_to_challenge_deleted() -> Weight;
	fn respond_to_challenge_superseded() -> Weight;
	fn confirm_replica_sync() -> Weight;
	fn top_up_replica_sync_balance() -> Weight;
}

/// Weights for `pallet_storage_provider` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn register_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3825`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(18_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn deregister_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `272`
		//  Estimated: `3825`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1001 w:1000)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn complete_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44971`
		//  Estimated: `2566553`
		// Minimum execution time: 4_052_000_000 picoseconds.
		Weight::from_parts(4_199_000_000, 2566553)
			.saturating_add(T::DbWeight::get().reads(1003_u64))
			.saturating_add(T::DbWeight::get().writes(1002_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn cancel_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `255`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_settings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn add_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `3825`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(17_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn block_extensions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `3825`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_multiaddr() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_bucket_min_providers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3823)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn freeze_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `3975`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3975)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn set_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `11515`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn remove_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `11515`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_slashed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `951`
		//  Estimated: `4416`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(27_000_000, 4416)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayState` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayState` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn establish_storage_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `11515`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(52_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayState` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayState` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn establish_replica_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `737`
		//  Estimated: `4202`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(53_000_000, 4202)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `643`
		//  Estimated: `3825`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(23_000_000, 3825)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn extend_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `746`
		//  Estimated: `6196`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(62_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 1]`.
	fn end_agreement(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1054 + a * (103 ±0)`
		//  Estimated: `6196 + a * (2603 ±0)`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(56_690_740, 6196)
			// Standard Error: 140_820
			.saturating_add(Weight::from_parts(24_681_481, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_expired_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1054`
		//  Estimated: `6196`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(56_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1697`
		//  Estimated: `15165`
		// Minimum execution time: 128_000_000 picoseconds.
		Weight::from_parts(143_000_000, 15165)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn extend_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1751`
		//  Estimated: `15165`
		// Minimum execution time: 127_000_000 picoseconds.
		Weight::from_parts(142_000_000, 15165)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn fund_checkpoint_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `253`
		//  Estimated: `3718`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3718)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 5]`.
	fn provider_checkpoint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493 + s * (258 ±0)`
		//  Estimated: `3958 + s * (2835 ±0)`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(19_988_877, 3958)
			// Standard Error: 70_760
			.saturating_add(Weight::from_parts(27_052_578, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 2835).saturating_mul(s.into()))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:0 w:1)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	fn configure_checkpoint_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3823)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn report_missed_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `896`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(38_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_checkpoint_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `4287`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(23_000_000, 4287)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn challenge_off_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `4098`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(52_000_000, 4098)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_replica() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `792`
		//  Estimated: `4257`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_000_000, 4257)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1060`
		//  Estimated: `6196`
		// Minimum execution time: 420_000_000 picoseconds.
		Weight::from_parts(469_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn respond_to_challenge_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1273`
		//  Estimated: `6660`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(63_000_000, 6660)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_superseded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1114`
		//  Estimated: `6196`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(35_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn confirm_replica_sync() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `973`
		//  Estimated: `6196`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(49_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn top_up_replica_sync_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `3692`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3692)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn register_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3825`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(18_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn deregister_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `272`
		//  Estimated: `3825`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1001 w:1000)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn complete_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44971`
		//  Estimated: `2566553`
		// Minimum execution time: 4_052_000_000 picoseconds.
		Weight::from_parts(4_199_000_000, 2566553)
			.saturating_add(RocksDbWeight::get().reads(1003_u64))
			.saturating_add(RocksDbWeight::get().writes(1002_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn cancel_deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `255`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_settings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn add_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `3825`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(17_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn block_extensions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `3825`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_multiaddr() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `251`
		//  Estimated: `3825`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_bucket_min_providers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3823)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn freeze_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `3975`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3975)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn set_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `11515`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 11515)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn remove_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `11515`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 11515)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_slashed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `951`
		//  Estimated: `4416`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(27_000_000, 4416)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayState` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayState` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn establish_storage_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `11515`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(52_000_000, 11515)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayState` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayState` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn establish_replica_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `737`
		//  Estimated: `4202`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(53_000_000, 4202)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `643`
		//  Estimated: `3825`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(23_000_000, 3825)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn extend_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `746`
		//  Estimated: `6196`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(62_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 1]`.
	fn end_agreement(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1054 + a * (103 ±0)`
		//  Estimated: `6196 + a * (2603 ±0)`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(56_690_740, 6196)
			// Standard Error: 140_820
			.saturating_add(Weight::from_parts(24_681_481, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_expired_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1054`
		//  Estimated: `6196`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(56_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1697`
		//  Estimated: `15165`
		// Minimum execution time: 128_000_000 picoseconds.
		Weight::from_parts(143_000_000, 15165)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn extend_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1751`
		//  Estimated: `15165`
		// Minimum execution time: 127_000_000 picoseconds.
		Weight::from_parts(142_000_000, 15165)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn fund_checkpoint_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `253`
		//  Estimated: `3718`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3718)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 5]`.
	fn provider_checkpoint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493 + s * (258 ±0)`
		//  Estimated: `3958 + s * (2835 ±0)`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(19_988_877, 3958)
			// Standard Error: 70_760
			.saturating_add(Weight::from_parts(27_052_578, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 2835).saturating_mul(s.into()))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:0 w:1)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	fn configure_checkpoint_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3823)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn report_missed_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `896`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(38_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_checkpoint_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `4287`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(23_000_000, 4287)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn challenge_off_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `4098`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(52_000_000, 4098)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_replica() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `792`
		//  Estimated: `4257`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(25_000_000, 4257)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1060`
		//  Estimated: `6196`
		// Minimum execution time: 420_000_000 picoseconds.
		Weight::from_parts(469_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn respond_to_challenge_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1273`
		//  Estimated: `6660`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(63_000_000, 6660)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_superseded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1114`
		//  Estimated: `6196`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(35_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn confirm_replica_sync() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `973`
		//  Estimated: `6196`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(49_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn top_up_replica_sync_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `510`
		//  Estimated: `3692`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3692)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}