[package]
name = "pallet-drive-registry"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Substrate pallet for Layer 1 drive registry"

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }
pallet-balances = { workspace = true }

# Local dependencies
file-system-primitives = { workspace = true }
storage-primitives = { workspace = true }
pallet-storage-provider = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-io/std",
    "pallet-balances/std",
    "file-system-primitives/std",
    "storage-primitives/std",
    "pallet-storage-provider/std",
]
