// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_s3_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `8758f4d2fa1a`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/storage-parachain-runtime/storage_parachain_runtime.wasm
// --pallet=pallet_s3_registry
// --header=/__w/web3-storage/web3-storage/scripts/cmd/file_header.txt
// --output=./runtime/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_s3_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_s3_registry::WeightInfo for WeightInfo<T> {
	/// Storage: `S3Registry::BucketNameToId` (r:1 w:1)
	/// Proof: `S3Registry::BucketNameToId` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::UserBuckets` (r:1 w:1)
	/// Proof: `S3Registry::UserBuckets` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayStates` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayStates` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::NextS3BucketId` (r:1 w:1)
	/// Proof: `S3Registry::NextS3BucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::S3Buckets` (r:0 w:1)
	/// Proof: `S3Registry::S3Buckets` (`max_values`: None, `max_size`: Some(158), added: 2633, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn create_s3_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1509`
		//  Estimated: `11515`
		// Minimum execution time: 116_705_000 picoseconds.
		Weight::from_parts(120_758_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `S3Registry::S3Buckets` (r:1 w:1)
	/// Proof: `S3Registry::S3Buckets` (`max_values`: None, `max_size`: Some(158), added: 2633, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::UserBuckets` (r:1 w:1)
	/// Proof: `S3Registry::UserBuckets` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::BucketNameToId` (r:0 w:1)
	/// Proof: `S3Registry::BucketNameToId` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	fn delete_s3_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1169`
		//  Estimated: `4315`
		// Minimum execution time: 21_020_000 picoseconds.
		Weight::from_parts(22_280_000, 0)
			.saturating_add(Weight::from_parts(0, 4315))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `S3Registry::S3Buckets` (r:1 w:1)
	/// Proof: `S3Registry::S3Buckets` (`max_values`: None, `max_size`: Some(158), added: 2633, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::Objects` (r:1 w:1)
	/// Proof: `S3Registry::Objects` (`max_values`: None, `max_size`: Some(7711), added: 10186, mode: `MaxEncodedLen`)
	fn put_object_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8038`
		//  Estimated: `11176`
		// Minimum execution time: 55_114_000 picoseconds.
		Weight::from_parts(56_807_000, 0)
			.saturating_add(Weight::from_parts(0, 11176))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `S3Registry::S3Buckets` (r:1 w:1)
	/// Proof: `S3Registry::S3Buckets` (`max_values`: None, `max_size`: Some(158), added: 2633, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::Objects` (r:1 w:1)
	/// Proof: `S3Registry::Objects` (`max_values`: None, `max_size`: Some(7711), added: 10186, mode: `MaxEncodedLen`)
	fn delete_object_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8038`
		//  Estimated: `11176`
		// Minimum execution time: 39_435_000 picoseconds.
		Weight::from_parts(40_912_000, 0)
			.saturating_add(Weight::from_parts(0, 11176))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `S3Registry::S3Buckets` (r:2 w:1)
	/// Proof: `S3Registry::S3Buckets` (`max_values`: None, `max_size`: Some(158), added: 2633, mode: `MaxEncodedLen`)
	/// Storage: `S3Registry::Objects` (r:2 w:1)
	/// Proof: `S3Registry::Objects` (`max_values`: None, `max_size`: Some(7711), added: 10186, mode: `MaxEncodedLen`)
	fn copy_object_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8205`
		//  Estimated: `21362`
		// Minimum execution time: 59_965_000 picoseconds.
		Weight::from_parts(62_151_000, 0)
			.saturating_add(Weight::from_parts(0, 21362))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
