// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `39a82f1f1afe`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/storage-parachain-runtime/storage_parachain_runtime.wasm
// --pallet=pallet_storage_provider
// --header=/__w/web3-storage/web3-storage/scripts/cmd/file_header.txt
// --output=./runtime/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_storage_provider`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_storage_provider::WeightInfo for WeightInfo<T> {
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn register_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3825`
		// Minimum execution time: 28_562_000 picoseconds.
		Weight::from_parts(30_074_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1001 w:1000)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn deregister_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45127`
		//  Estimated: `2566553`
		// Minimum execution time: 7_065_206_000 picoseconds.
		Weight::from_parts(7_138_759_000, 0)
			.saturating_add(Weight::from_parts(0, 2566553))
			.saturating_add(T::DbWeight::get().reads(1003))
			.saturating_add(T::DbWeight::get().writes(1002))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_settings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324`
		//  Estimated: `3825`
		// Minimum execution time: 12_389_000 picoseconds.
		Weight::from_parts(13_296_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn add_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `3825`
		// Minimum execution time: 26_906_000 picoseconds.
		Weight::from_parts(28_316_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn block_extensions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `362`
		//  Estimated: `3825`
		// Minimum execution time: 17_243_000 picoseconds.
		Weight::from_parts(18_323_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn update_provider_multiaddr() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324`
		//  Estimated: `3825`
		// Minimum execution time: 12_792_000 picoseconds.
		Weight::from_parts(13_750_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `160`
		//  Estimated: `11515`
		// Minimum execution time: 16_294_000 picoseconds.
		Weight::from_parts(17_528_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn create_bucket_with_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `11515`
		// Minimum execution time: 50_531_000 picoseconds.
		Weight::from_parts(53_103_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_bucket_min_providers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3894`
		// Minimum execution time: 10_220_000 picoseconds.
		Weight::from_parts(11_017_000, 0)
			.saturating_add(Weight::from_parts(0, 3894))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn freeze_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `581`
		//  Estimated: `4046`
		// Minimum execution time: 14_590_000 picoseconds.
		Weight::from_parts(15_684_000, 0)
			.saturating_add(Weight::from_parts(0, 4046))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn set_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `11515`
		// Minimum execution time: 18_753_000 picoseconds.
		Weight::from_parts(19_875_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn remove_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `602`
		//  Estimated: `11515`
		// Minimum execution time: 19_984_000 picoseconds.
		Weight::from_parts(21_235_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_slashed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `985`
		//  Estimated: `4450`
		// Minimum execution time: 44_190_000 picoseconds.
		Weight::from_parts(46_371_000, 0)
			.saturating_add(Weight::from_parts(0, 4450))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	fn request_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `612`
		//  Estimated: `4077`
		// Minimum execution time: 37_301_000 picoseconds.
		Weight::from_parts(39_124_000, 0)
			.saturating_add(Weight::from_parts(0, 4077))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	fn request_primary_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `774`
		//  Estimated: `4239`
		// Minimum execution time: 38_262_000 picoseconds.
		Weight::from_parts(40_080_000, 0)
			.saturating_add(Weight::from_parts(0, 4239))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn accept_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `833`
		//  Estimated: `4298`
		// Minimum execution time: 33_111_000 picoseconds.
		Weight::from_parts(35_163_000, 0)
			.saturating_add(Weight::from_parts(0, 4298))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn reject_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3622`
		// Minimum execution time: 27_484_000 picoseconds.
		Weight::from_parts(29_107_000, 0)
			.saturating_add(Weight::from_parts(0, 3622))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_agreement_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3622`
		// Minimum execution time: 29_190_000 picoseconds.
		Weight::from_parts(30_632_000, 0)
			.saturating_add(Weight::from_parts(0, 3622))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `606`
		//  Estimated: `3825`
		// Minimum execution time: 36_014_000 picoseconds.
		Weight::from_parts(37_606_000, 0)
			.saturating_add(Weight::from_parts(0, 3825))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn extend_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `709`
		//  Estimated: `6196`
		// Minimum execution time: 82_819_000 picoseconds.
		Weight::from_parts(85_745_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 1]`.
	fn end_agreement(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1088 + a * (103 ±0)`
		//  Estimated: `6196 + a * (2603 ±0)`
		// Minimum execution time: 83_246_000 picoseconds.
		Weight::from_parts(86_337_271, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 177_580
			.saturating_add(Weight::from_parts(35_108_278, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_expired_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1088`
		//  Estimated: `6196`
		// Minimum execution time: 80_532_000 picoseconds.
		Weight::from_parts(83_610_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1768`
		//  Estimated: `15165`
		// Minimum execution time: 269_055_000 picoseconds.
		Weight::from_parts(275_805_000, 0)
			.saturating_add(Weight::from_parts(0, 15165))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn extend_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1822`
		//  Estimated: `15165`
		// Minimum execution time: 258_848_000 picoseconds.
		Weight::from_parts(266_468_000, 0)
			.saturating_add(Weight::from_parts(0, 15165))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn fund_checkpoint_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324`
		//  Estimated: `3789`
		// Minimum execution time: 30_810_000 picoseconds.
		Weight::from_parts(32_467_000, 0)
			.saturating_add(Weight::from_parts(0, 3789))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 5]`.
	fn provider_checkpoint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `564 + s * (258 ±0)`
		//  Estimated: `4029 + s * (2835 ±0)`
		// Minimum execution time: 84_540_000 picoseconds.
		Weight::from_parts(38_501_295, 0)
			.saturating_add(Weight::from_parts(0, 4029))
			// Standard Error: 59_434
			.saturating_add(Weight::from_parts(49_199_173, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 2835).saturating_mul(s.into()))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:0 w:1)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	fn configure_checkpoint_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3894`
		// Minimum execution time: 13_549_000 picoseconds.
		Weight::from_parts(14_503_000, 0)
			.saturating_add(Weight::from_parts(0, 3894))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn report_missed_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `967`
		//  Estimated: `6196`
		// Minimum execution time: 61_139_000 picoseconds.
		Weight::from_parts(64_118_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_checkpoint_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 29_491_000 picoseconds.
		Weight::from_parts(31_065_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `893`
		//  Estimated: `4358`
		// Minimum execution time: 36_307_000 picoseconds.
		Weight::from_parts(38_230_000, 0)
			.saturating_add(Weight::from_parts(0, 4358))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn challenge_off_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `667`
		//  Estimated: `4132`
		// Minimum execution time: 87_282_000 picoseconds.
		Weight::from_parts(90_296_000, 0)
			.saturating_add(Weight::from_parts(0, 4132))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn challenge_replica() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `755`
		//  Estimated: `4220`
		// Minimum execution time: 38_319_000 picoseconds.
		Weight::from_parts(40_392_000, 0)
			.saturating_add(Weight::from_parts(0, 4220))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1131`
		//  Estimated: `6196`
		// Minimum execution time: 1_131_556_000 picoseconds.
		Weight::from_parts(1_143_714_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn respond_to_challenge_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1344`
		//  Estimated: `6660`
		// Minimum execution time: 112_647_000 picoseconds.
		Weight::from_parts(117_117_000, 0)
			.saturating_add(Weight::from_parts(0, 6660))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	fn respond_to_challenge_superseded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1185`
		//  Estimated: `6196`
		// Minimum execution time: 59_087_000 picoseconds.
		Weight::from_parts(61_811_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn confirm_replica_sync() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1008`
		//  Estimated: `6196`
		// Minimum execution time: 72_721_000 picoseconds.
		Weight::from_parts(75_305_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn top_up_replica_sync_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `473`
		//  Estimated: `3692`
		// Minimum execution time: 29_796_000 picoseconds.
		Weight::from_parts(31_250_000, 0)
			.saturating_add(Weight::from_parts(0, 3692))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
