// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_storage_provider`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-06-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `3b56c63788c6`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/storage-parachain-runtime/storage_parachain_runtime.wasm
// --pallet=pallet_storage_provider
// --header=/__w/web3-storage/web3-storage/scripts/cmd/file_header.txt
// --output=./runtime/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_storage_provider`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_storage_provider::WeightInfo for WeightInfo<T> {
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn register_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3820`
		// Minimum execution time: 28_942_000 picoseconds.
		Weight::from_parts(30_497_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1001 w:1000)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn deregister_provider() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45122`
		//  Estimated: `2566553`
		// Minimum execution time: 7_021_994_000 picoseconds.
		Weight::from_parts(7_127_428_000, 0)
			.saturating_add(Weight::from_parts(0, 2566553))
			.saturating_add(T::DbWeight::get().reads(1003))
			.saturating_add(T::DbWeight::get().writes(1002))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn update_provider_settings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `323`
		//  Estimated: `3820`
		// Minimum execution time: 12_480_000 picoseconds.
		Weight::from_parts(13_370_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn add_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `426`
		//  Estimated: `3820`
		// Minimum execution time: 27_277_000 picoseconds.
		Weight::from_parts(28_509_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn block_extensions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `362`
		//  Estimated: `3820`
		// Minimum execution time: 17_268_000 picoseconds.
		Weight::from_parts(18_317_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn update_provider_multiaddr() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `323`
		//  Estimated: `3820`
		// Minimum execution time: 12_763_000 picoseconds.
		Weight::from_parts(13_641_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `160`
		//  Estimated: `11515`
		// Minimum execution time: 16_546_000 picoseconds.
		Weight::from_parts(17_525_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn create_bucket_with_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `504`
		//  Estimated: `11515`
		// Minimum execution time: 51_636_000 picoseconds.
		Weight::from_parts(54_301_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_bucket_min_providers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3894`
		// Minimum execution time: 10_256_000 picoseconds.
		Weight::from_parts(10_993_000, 0)
			.saturating_add(Weight::from_parts(0, 3894))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn freeze_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `581`
		//  Estimated: `4046`
		// Minimum execution time: 14_583_000 picoseconds.
		Weight::from_parts(15_552_000, 0)
			.saturating_add(Weight::from_parts(0, 4046))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn set_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `11515`
		// Minimum execution time: 18_834_000 picoseconds.
		Weight::from_parts(19_901_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn remove_bucket_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `602`
		//  Estimated: `11515`
		// Minimum execution time: 20_479_000 picoseconds.
		Weight::from_parts(21_582_000, 0)
			.saturating_add(Weight::from_parts(0, 11515))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_slashed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `984`
		//  Estimated: `4449`
		// Minimum execution time: 44_249_000 picoseconds.
		Weight::from_parts(46_417_000, 0)
			.saturating_add(Weight::from_parts(0, 4449))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	fn request_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `611`
		//  Estimated: `4076`
		// Minimum execution time: 37_513_000 picoseconds.
		Weight::from_parts(39_420_000, 0)
			.saturating_add(Weight::from_parts(0, 4076))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	fn request_primary_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `773`
		//  Estimated: `4238`
		// Minimum execution time: 38_821_000 picoseconds.
		Weight::from_parts(40_504_000, 0)
			.saturating_add(Weight::from_parts(0, 4238))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn accept_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `832`
		//  Estimated: `4297`
		// Minimum execution time: 31_586_000 picoseconds.
		Weight::from_parts(33_194_000, 0)
			.saturating_add(Weight::from_parts(0, 4297))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn reject_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3622`
		// Minimum execution time: 27_474_000 picoseconds.
		Weight::from_parts(29_374_000, 0)
			.saturating_add(Weight::from_parts(0, 3622))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::AgreementRequests` (r:1 w:1)
	/// Proof: `StorageProvider::AgreementRequests` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_agreement_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `380`
		//  Estimated: `3622`
		// Minimum execution time: 29_647_000 picoseconds.
		Weight::from_parts(30_969_000, 0)
			.saturating_add(Weight::from_parts(0, 3622))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn top_up_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `605`
		//  Estimated: `3820`
		// Minimum execution time: 36_476_000 picoseconds.
		Weight::from_parts(38_256_000, 0)
			.saturating_add(Weight::from_parts(0, 3820))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn extend_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `708`
		//  Estimated: `6196`
		// Minimum execution time: 83_794_000 picoseconds.
		Weight::from_parts(87_585_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[0, 1]`.
	fn end_agreement(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1087 + a * (103 ±0)`
		//  Estimated: `6196 + a * (2603 ±0)`
		// Minimum execution time: 84_480_000 picoseconds.
		Weight::from_parts(87_822_440, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 133_565
			.saturating_add(Weight::from_parts(36_208_209, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_expired_agreement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1087`
		//  Estimated: `6196`
		// Minimum execution time: 81_168_000 picoseconds.
		Weight::from_parts(85_479_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1763`
		//  Estimated: `15140`
		// Minimum execution time: 259_951_000 picoseconds.
		Weight::from_parts(267_834_000, 0)
			.saturating_add(Weight::from_parts(0, 15140))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn extend_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1817`
		//  Estimated: `15140`
		// Minimum execution time: 259_780_000 picoseconds.
		Weight::from_parts(266_270_000, 0)
			.saturating_add(Weight::from_parts(0, 15140))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn fund_checkpoint_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324`
		//  Estimated: `3789`
		// Minimum execution time: 30_781_000 picoseconds.
		Weight::from_parts(32_629_000, 0)
			.saturating_add(Weight::from_parts(0, 3789))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:5 w:0)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointPool` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointPool` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 5]`.
	fn provider_checkpoint(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `564 + s * (257 ±0)`
		//  Estimated: `4029 + s * (2830 ±0)`
		// Minimum execution time: 83_995_000 picoseconds.
		Weight::from_parts(37_791_691, 0)
			.saturating_add(Weight::from_parts(0, 4029))
			// Standard Error: 76_575
			.saturating_add(Weight::from_parts(49_634_860, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 2830).saturating_mul(s.into()))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:0 w:1)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	fn configure_checkpoint_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `429`
		//  Estimated: `3894`
		// Minimum execution time: 13_565_000 picoseconds.
		Weight::from_parts(14_410_000, 0)
			.saturating_add(Weight::from_parts(0, 3894))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::CheckpointConfigs` (r:1 w:0)
	/// Proof: `StorageProvider::CheckpointConfigs` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::LastCheckpointWindow` (r:1 w:1)
	/// Proof: `StorageProvider::LastCheckpointWindow` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn report_missed_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `966`
		//  Estimated: `6196`
		// Minimum execution time: 61_064_000 picoseconds.
		Weight::from_parts(63_889_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::CheckpointRewards` (r:1 w:1)
	/// Proof: `StorageProvider::CheckpointRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_checkpoint_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 29_751_000 picoseconds.
		Weight::from_parts(31_247_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn challenge_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `892`
		//  Estimated: `4357`
		// Minimum execution time: 36_853_000 picoseconds.
		Weight::from_parts(38_564_000, 0)
			.saturating_add(Weight::from_parts(0, 4357))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn challenge_off_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `4131`
		// Minimum execution time: 87_472_000 picoseconds.
		Weight::from_parts(91_100_000, 0)
			.saturating_add(Weight::from_parts(0, 4131))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:0)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn challenge_replica() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `4219`
		// Minimum execution time: 38_557_000 picoseconds.
		Weight::from_parts(40_844_000, 0)
			.saturating_add(Weight::from_parts(0, 4219))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn respond_to_challenge_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1130`
		//  Estimated: `6196`
		// Minimum execution time: 1_147_745_000 picoseconds.
		Weight::from_parts(1_158_616_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Providers` (r:2 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn respond_to_challenge_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1342`
		//  Estimated: `6650`
		// Minimum execution time: 113_313_000 picoseconds.
		Weight::from_parts(116_781_000, 0)
			.saturating_add(Weight::from_parts(0, 6650))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Challenges` (r:1 w:1)
	/// Proof: `StorageProvider::Challenges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn respond_to_challenge_superseded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1184`
		//  Estimated: `6196`
		// Minimum execution time: 59_432_000 picoseconds.
		Weight::from_parts(61_894_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `StorageProvider::Buckets` (r:1 w:0)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn confirm_replica_sync() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1008`
		//  Estimated: `6196`
		// Minimum execution time: 72_583_000 picoseconds.
		Weight::from_parts(76_841_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::StorageAgreements` (r:1 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn top_up_replica_sync_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `473`
		//  Estimated: `3692`
		// Minimum execution time: 30_122_000 picoseconds.
		Weight::from_parts(31_693_000, 0)
			.saturating_add(Weight::from_parts(0, 3692))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
