[package]
name = "storage-primitives"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "Shared primitives for scalable Web3 storage"

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
serde = { workspace = true, optional = true }
fastcdc = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["std"]
std = ["codec/std", "dep:fastcdc", "scale-info/std", "serde/std", "sp-core/std"]
serde = ["dep:serde", "sp-core/serde"]
