// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_drive_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.0.104`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/storage-parachain-runtime/storage_parachain_runtime.wasm
// --pallet=pallet_drive_registry
// --header=/Users/huytung/Documents/web3-storage/scripts/cmd/file_header.txt
// --output=./runtime/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --min-duration
// 1

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;
use frame_support::weights::constants::RocksDbWeight;

/// Weight functions for `pallet_drive_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_drive_registry::WeightInfo for WeightInfo<T> {
		/// Storage: `DriveRegistry::UserDrives` (r:1 w:1)
	/// Proof: `DriveRegistry::UserDrives` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::ProviderReplayState` (r:1 w:1)
	/// Proof: `StorageProvider::ProviderReplayState` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::NextBucketId` (r:1 w:1)
	/// Proof: `StorageProvider::NextBucketId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `DriveRegistry::NextDriveId` (r:1 w:1)
	/// Proof: `DriveRegistry::NextDriveId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `DriveRegistry::BucketToDrive` (r:0 w:1)
	/// Proof: `DriveRegistry::BucketToDrive` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `DriveRegistry::Drives` (r:0 w:1)
	/// Proof: `DriveRegistry::Drives` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:0 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:0 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	fn create_drive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1301`
		//  Estimated: `11515`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(64_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `DriveRegistry::Drives` (r:1 w:1)
	/// Proof: `DriveRegistry::Drives` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::StorageAgreements` (r:2 w:1)
	/// Proof: `StorageProvider::StorageAgreements` (`max_values`: None, `max_size`: Some(227), added: 2702, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Providers` (r:1 w:1)
	/// Proof: `StorageProvider::Providers` (`max_values`: None, `max_size`: Some(360), added: 2835, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::MemberBuckets` (r:100 w:100)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `DriveRegistry::UserDrives` (r:1 w:1)
	/// Proof: `DriveRegistry::UserDrives` (`max_values`: None, `max_size`: Some(850), added: 3325, mode: `MaxEncodedLen`)
	/// Storage: `DriveRegistry::BucketToDrive` (r:0 w:1)
	/// Proof: `DriveRegistry::BucketToDrive` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn delete_drive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12052`
		//  Estimated: `1053490`
		// Minimum execution time: 331_000_000 picoseconds.
		Weight::from_parts(367_000_000, 1053490)
			.saturating_add(T::DbWeight::get().reads(108_u64))
			.saturating_add(T::DbWeight::get().writes(108_u64))
	}
	/// Storage: `DriveRegistry::Drives` (r:1 w:0)
	/// Proof: `DriveRegistry::Drives` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn share_drive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4757`
		//  Estimated: `11515`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(21_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `DriveRegistry::Drives` (r:1 w:0)
	/// Proof: `DriveRegistry::Drives` (`max_values`: None, `max_size`: Some(215), added: 2690, mode: `MaxEncodedLen`)
	/// Storage: `StorageProvider::Buckets` (r:1 w:1)
	/// Proof: `StorageProvider::Buckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `StorageProvider::MemberBuckets` (r:1 w:1)
	/// Proof: `StorageProvider::MemberBuckets` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	fn unshare_drive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4784`
		//  Estimated: `11515`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(22_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}
