name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI_IMAGE: "paritytech/ci-unified:bullseye-1.88.0-2025-06-27-v202507112050"

jobs:
  set-image:
    runs-on: ubuntu-latest
    outputs:
      CI_IMAGE: ${{ steps.set_image.outputs.CI_IMAGE }}
    steps:
      - id: set_image
        run: echo "CI_IMAGE=${{ env.CI_IMAGE }}" >> $GITHUB_OUTPUT

  check-fmt:
    runs-on: parity-default
    timeout-minutes: 20
    continue-on-error: true
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.CI_IMAGE }}
    steps:
      - uses: actions/checkout@v6

      - name: Cargo fmt
        run: |
          rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
          cargo +nightly fmt --all -- --check

      - name: Check TOML format
        run: |
          cargo install taplo-cli && taplo --version
          if ! taplo format --check --config .config/taplo.toml; then
            echo "Please run 'taplo format --config .config/taplo.toml' to fix any TOML formatting issues"
            exit 1
          fi
          cargo install --locked zepter && zepter --version
          if ! zepter run check --config .config/zepter.yaml; then
            echo "Please run 'zepter run --config .config/zepter.yaml' to fix any TOML formatting issues"
            exit 1
          fi

  check:
    name: Cargo check
    runs-on: parity-large
    needs: [set-image]
    container:
      image: ${{ needs.set-image.outputs.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "web3-storage-cache-check"
          save-if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

      - name: Cargo check
        run: |
          cargo check --workspace --quiet
          cargo check --workspace --features=runtime-benchmarks --quiet
          cargo check --workspace --features=try-runtime --quiet

  clippy:
    name: Cargo clippy
    runs-on: parity-default
    continue-on-error: true
    needs: [set-image, check]
    container:
      image: ${{ needs.set-image.outputs.CI_IMAGE }}
    env:
      RUSTFLAGS: "-D warnings"
      SKIP_WASM_BUILD: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "web3-storage-cache-clippy"
          save-if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

      - name: Cargo clippy
        run: |
          cargo clippy --all-targets --locked --workspace --quiet
          cargo clippy --all-targets --all-features --locked --workspace --quiet

  test:
    name: Test
    runs-on: parity-large
    timeout-minutes: 60
    needs: [set-image, check]
    container:
      image: ${{ needs.set-image.outputs.CI_IMAGE }}
    env:
      SKIP_WASM_BUILD: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "web3-storage-cache-tests"
          save-if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}

      - name: Run tests
        run: |
          cargo test --workspace
