name: Command

on:
  issue_comment: # listen for comments on issues
    types: [created]

# Least-privilege by default — each job grants only the scopes it needs.
permissions: {}

jobs:
  is-org-member:
    if: startsWith(github.event.comment.body, '/cmd')
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      member: ${{ steps.is-member.outputs.result }}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.CMD_BOT_APP_ID }}
          private-key: ${{ secrets.CMD_BOT_APP_KEY }}
          permission-members: read

      - name: Check if user is a member of the organization
        id: is-member
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          ORG: ${{ github.event.repository.owner.login }}
          COMMENT_USER: ${{ github.event.comment.user.login }}
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          result-encoding: string
          script: |
            const fs = require("fs");
            try {
              const org = process.env.ORG;
              const username = process.env.COMMENT_USER;

              const membership = await github.rest.orgs.checkMembershipForUser({
                  org: org,
                  username: username
              });

              console.log(membership, membership.status, membership.status === 204);

              if (membership.status === 204) {
                return 'true';
              } else {
                console.log(membership);
                fs.appendFileSync(process.env["GITHUB_STEP_SUMMARY"], `${membership.data && membership.data.message || 'Unknown error happened, please check logs'}`);
              }
            } catch (error) {
              console.log(error)
            }

            return 'false';

  acknowledge:
    if: ${{ startsWith(github.event.comment.body, '/cmd') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add reaction to triggered comment
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: ${{ github.event.comment.id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: 'eyes'
            })

  clean:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Clean previous comments
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ startsWith(github.event.comment.body, '/cmd') && contains(github.event.comment.body, '--clean') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            }).then(comments => {
              for (let comment of comments.data) {
                console.log(comment)
                if (
                  ${{ github.event.comment.id }} !== comment.id &&
                    (
                      (
                        (
                          comment.body.startsWith('Command') ||
                          comment.body.startsWith('<details><summary>Command') ||
                          comment.body.startsWith('Sorry, only ')
                        ) && comment.user.type === 'Bot'
                      ) ||
                      (comment.body.startsWith('/cmd') && comment.user.login === context.actor)
                    )
                ) {
                  github.rest.issues.deleteComment({
                    comment_id: comment.id,
                    owner: context.repo.owner,
                    repo: context.repo.repo
                  })
                }
              }
            })

  get-pr-info:
    if: ${{ startsWith(github.event.comment.body, '/cmd') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      CMD: ${{ steps.get-comment.outputs.group2 }}
      pr-branch: ${{ steps.get-pr.outputs.pr_branch }}
      repo: ${{ steps.get-pr.outputs.repo }}
    steps:
      - name: Get command
        id: get-comment
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        with:
          script: |
            // see explanation in docs/contributor/commands-readme.md#examples
            const match = process.env.COMMENT_BODY.match(/^(\/cmd )([-\/\s\w.=:]+)$/);
            core.setOutput('group2', match ? match[2] : '');

      # Get PR branch name, because the issue_comment event does not contain the PR branch name
      - name: Check if the issue is a PR
        id: check-pr
        env:
          PR_URL: ${{ github.event.issue.pull_request.url }}
        run: |
          if [ -n "$PR_URL" ]; then
            echo "This is a pull request comment"
          else
            echo "This is not a pull request comment"
            exit 1
          fi

      - name: Get PR Branch Name and Repo
        if: steps.check-pr.outcome == 'success'
        id: get-pr
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            const prBranch = pr.data.head.ref;
            const repo = pr.data.head.repo.full_name;
            console.log(prBranch, repo)
            core.setOutput('pr_branch', prBranch);
            core.setOutput('repo', repo);

      - name: Use PR Branch Name and Repo
        env:
          PR_BRANCH: ${{ steps.get-pr.outputs.pr_branch }}
          REPO: ${{ steps.get-pr.outputs.repo }}
          CMD: ${{ steps.get-comment.outputs.group2 }}
        run: |
          echo "The PR branch is $PR_BRANCH"
          echo "The repository is $REPO"
          echo "The CMD is $CMD"

  help:
    needs: [clean, get-pr-info]
    if: ${{ startsWith(github.event.comment.body, '/cmd') && contains(github.event.comment.body, '--help') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Save output of help
        id: help
        env:
          CMD: ${{ needs.get-pr-info.outputs.CMD }} # to avoid "" around the command
        run: |
          echo 'help<<EOF' >> $GITHUB_OUTPUT
          python3 scripts/cmd/cmd.py $CMD >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Comment PR (Help)
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          HELP_OUTPUT: ${{ steps.help.outputs.help }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<details><summary>Command help:</summary>

            \`\`\`
            ${process.env.HELP_OUTPUT}
            \`\`\`

            </details>`
            })

      - name: Add confused reaction on failure
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: ${{ github.event.comment.id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: 'confused'
            })

      - name: Add 👍 reaction on success
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ !failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: ${{ github.event.comment.id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1'
            })

  set-image:
    needs: [clean, get-pr-info]
    if: ${{ startsWith(github.event.comment.body, '/cmd') && !contains(github.event.comment.body, '--help') }}
    permissions:
      contents: read
    uses: ./.github/workflows/set-image.yml

  set-runner:
    needs: [get-pr-info, set-image]
    if: ${{ startsWith(github.event.comment.body, '/cmd') && !contains(github.event.comment.body, '--help') }}
    runs-on: ubuntu-latest
    permissions: {}
    env:
      CMD: ${{ needs.get-pr-info.outputs.CMD }}
      DEFAULT_IMAGE: ${{ needs.set-image.outputs.CI_IMAGE }}
    outputs:
      IMAGE: ${{ steps.set-image.outputs.IMAGE }}
      RUNNER: ${{ steps.set-image.outputs.RUNNER }}
    steps:
      - id: set-image
        run: |
          BODY=$(echo "$CMD" | xargs) # remove whitespace
          IMAGE_OVERRIDE=$(echo "$BODY" | grep -oe 'docker.io/paritytech/ci-unified:[^[:space:]]*' || true)

          if [ -n "$IMAGE_OVERRIDE" ]; then
              echo "IMAGE=$IMAGE_OVERRIDE" >> $GITHUB_OUTPUT
          else
              echo "IMAGE=$DEFAULT_IMAGE" >> $GITHUB_OUTPUT
          fi

          if [[ $BODY == "bench"* ]]; then
              echo "RUNNER=parity-weights" >> $GITHUB_OUTPUT
          elif [[ $BODY == "update-ui"* ]]; then
              echo "RUNNER=parity-large" >> $GITHUB_OUTPUT
          else
              echo "RUNNER=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

      - name: Print outputs
        env:
          RUNNER: ${{ steps.set-image.outputs.RUNNER }}
          IMAGE: ${{ steps.set-image.outputs.IMAGE }}
        run: |
          echo "RUNNER=$RUNNER"
          echo "IMAGE=$IMAGE"

  run-cmd-workflow:
    needs: [set-runner, get-pr-info, is-org-member]
    runs-on: ubuntu-latest
    # don't run on help; require the commenter to be an org member
    if: ${{ startsWith(github.event.comment.body, '/cmd') && !contains(github.event.comment.body, '--help') && needs.is-org-member.outputs.member == 'true' }}
    permissions: # dispatch cmd-run.yml
      contents: read
      actions: write
    env:
      CMD: ${{ needs.get-pr-info.outputs.CMD }}
      PR_BRANCH: ${{ needs.get-pr-info.outputs.pr-branch }}
      RUNNER: ${{ needs.set-runner.outputs.RUNNER }}
      IMAGE: ${{ needs.set-runner.outputs.IMAGE }}
      REPO: ${{ needs.get-pr-info.outputs.repo }}
      IS_ORG_MEMBER: ${{ needs.is-org-member.outputs.member }}
      COMMENT_ID: ${{ github.event.comment.id }}
      PR_NUMBER: ${{ github.event.issue.number }}
      IS_QUIET: ${{ contains(github.event.comment.body, '--quiet') }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Start cmd with gh cli
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run cmd-run.yml \
            --ref cmd-bot \
            -f cmd="${CMD}" \
            -f repo="${REPO}" \
            -f pr_branch="${PR_BRANCH}" \
            -f pr_num="${PR_NUMBER}" \
            -f runner="${RUNNER}" \
            -f is_org_member="${IS_ORG_MEMBER}" \
            -f comment_id="${COMMENT_ID}" \
            -f image="${IMAGE}" \
            -f is_quiet="${IS_QUIET}"